In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
plt.style.use('seaborn-v0_8')
sns.set_palette('husl')

In [4]:
df1 = pd.read_csv("C:/Users/diksh/OneDrive/Desktop/Highway_safety_dashboard/data/combined_accident_data.csv")

In [5]:
print("Shape:",df1.shape)
print("Rows",df1.shape[0])
print("Columns:",df1.shape[1])

Shape: (1000, 29)
Rows 1000
Columns: 29

In [7]:
df1.head()

,Num_Acc,inverse_data,week_day,state,severity,weather,location,hrmn,lum,vehicle_type,vehicle_model,engine_size,driver_sex,driver_age,car_age,casualty_severity,casualty_age,casualty_sex,social_class,casualty_type,pedestrian_or_passenger,severity_description,weather_description,location_description,vehicle_type_description,engine_size_description,driver_sex_description,casualty_severity_description,casualty_type_description
0,AID0001,2022-11-20,T,WB,Minor,Storm,Loc91,1958,Daylight,Car,Model41,1089,M,48,20,Fatal,33,M,Upper,Pedestrian,Pedestrian,"Severity of the accident (Minor, Moderate, Sev...","Weather conditions during the accident (Clear,...",Location ID of accident spot,Type of vehicle involved in the accident,Engine size of the vehicle involved,Gender of the driver involved,"Severity of the casualty (Slight, Serious, Fatal)","Type of casualty (Pedestrian, Car Passenger, C..."
1,AID0002,2023-12-09,T,TR,Severe,Fog,Loc184,2245,Daylight,Car,Model1,2653,F,21,10,Slight,9,M,Middle,Pedestrian,Pedestrian,"Severity of the accident (Minor, Moderate, Sev...","Weather conditions during the accident (Clear,...",Location ID of accident spot,Type of vehicle involved in the accident,Engine size of the vehicle involved,Gender of the driver involved,"Severity of the casualty (Slight, Serious, Fatal)","Type of casualty (Pedestrian, Car Passenger, C..."
2,AID0003,2022-11-12,W,HP,Moderate,Fog,Loc77,250,Twilight,Car,Model21,2997,M,62,6,Slight,45,F,Working,Car Passenger,Pedestrian,"Severity of the accident (Minor, Moderate, Sev...","Weather conditions during the accident (Clear,...",Location ID of accident spot,Type of vehicle involved in the accident,Engine size of the vehicle involved,Gender of the driver involved,"Severity of the casualty (Slight, Serious, Fatal)","Type of casualty (Pedestrian, Car Passenger, C..."
3,AID0004,2023-02-13,T,CG,Severe,Clear,Loc78,545,Night,Motorcycle,Model30,2079,M,26,18,Serious,59,M,Working,Motorcyclist,Pedestrian,"Severity of the accident (Minor, Moderate, Sev...","Weather conditions during the accident (Clear,...",Location ID of accident spot,Type of vehicle involved in the accident,Engine size of the vehicle involved,Gender of the driver involved,"Severity of the casualty (Slight, Serious, Fatal)","Type of casualty (Pedestrian, Car Passenger, C..."
4,AID0005,2022-11-25,S,TR,Moderate,Storm,Loc57,2146,Twilight,Car,Model23,2279,M,20,2,Serious,30,F,Working,Cyclist,Pedestrian,"Severity of the accident (Minor, Moderate, Sev...","Weather conditions during the accident (Clear,...",Location ID of accident spot,Type of vehicle involved in the accident,Engine size of the vehicle involved,Gender of the driver involved,"Severity of the casualty (Slight, Serious, Fatal)","Type of casualty (Pedestrian, Car Passenger, C..."

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Num_Acc                        1000 non-null   object
 1   inverse_data                   1000 non-null   object
 2   week_day                       1000 non-null   object
 3   state                          1000 non-null   object
 4   severity                       1000 non-null   object
 5   weather                        1000 non-null   object
 6   location                       1000 non-null   object
 7   hrmn                           1000 non-null   int64
 8   lum                            1000 non-null   object
 9   vehicle_type                   1000 non-null   object
 10  vehicle_model                  1000 non-null   object
 11  engine_size                    1000 non-null   int64
 12  driver_sex                     1000 non-null   object
 13  driver_age                     1000 non-null   int64
 14  car_age                        1000 non-null   int64
 15  casualty_severity              1000 non-null   object
 16  casualty_age                   1000 non-null   int64
 17  casualty_sex                   1000 non-null   object
 18  social_class                   1000 non-null   object
 19  casualty_type                  1000 non-null   object
 20  pedestrian_or_passenger        1000 non-null   object
 21  severity_description           1000 non-null   object
 22  weather_description            1000 non-null   object
 23  location_description           1000 non-null   object
 24  vehicle_type_description       1000 non-null   object
 25  engine_size_description        1000 non-null   object
 26  driver_sex_description         1000 non-null   object
 27  casualty_severity_description  1000 non-null   object
 28  casualty_type_description      1000 non-null   object
dtypes: int64(5), object(24)
memory usage: 226.7+ KB

In [10]:
df1.isnull().sum()

Num_Acc                          0
inverse_data                     0
week_day                         0
state                            0
severity                         0
weather                          0
location                         0
hrmn                             0
lum                              0
vehicle_type                     0
vehicle_model                    0
engine_size                      0
driver_sex                       0
driver_age                       0
car_age                          0
casualty_severity                0
casualty_age                     0
casualty_sex                     0
social_class                     0
casualty_type                    0
pedestrian_or_passenger          0
severity_description             0
weather_description              0
location_description             0
vehicle_type_description         0
engine_size_description          0
driver_sex_description           0
casualty_severity_description    0
casualty_type_description        0
dtype: int64

In [11]:
df1.describe()

              hrmn  engine_size   driver_age      car_age  casualty_age
count  1000.000000  1000.000000  1000.000000  1000.000000    1000.00000
mean   1174.884000  1894.821000    44.234000     9.992000      40.86700
std     675.151316   628.284385    15.301221     6.020646      22.85405
min       1.000000   800.000000    18.000000     0.000000       1.00000
25%     557.000000  1328.000000    31.000000     5.000000      21.00000
50%    1143.000000  1901.000000    44.000000    10.000000      41.00000
75%    1753.250000  2439.250000    58.000000    15.000000      60.00000
max    2359.000000  2997.000000    70.000000    20.000000      80.00000

In [12]:
#Dropping the descriptive columns
desc_cols=['severity_description', 'weather_description', 'location_description',
             'vehicle_type_description', 'engine_size_description',
             'driver_sex_description', 'casualty_severity_description',
             'casualty_type_description']
df1.drop(columns = desc_cols,inplace = True)
print("New Shape",df1.shape)

New Shape (1000, 21)

In [15]:
df1.rename(columns={'Num_Acc':'accident_id',
                    'inverse_data':'date',
                    'hrmn':'time',
                    'lum':'light_condition'
                   },inplace = True )
print(df1.columns.tolist())

['accident_id', 'date', 'week_day', 'state', 'severity', 'weather', 'location', 'time', 'light_condition', 'vehicle_type', 'vehicle_model', 'engine_size', 'driver_sex', 'driver_age', 'car_age', 'casualty_severity', 'casualty_age', 'casualty_sex', 'social_class', 'casualty_type', 'pedestrian_or_passenger']

In [20]:
df1['date'] = pd.to_datetime(df1['date'])
df1['year'] = df1['date'].dt.year
df1['month'] = df1['date'].dt.month
df1['month_name'] = df1['date'].dt.strftime('%B')
df1[['date','year','month','month_name']].head()

        date  year  month month_name
0 2022-11-20  2022     11   November
1 2023-12-09  2023     12   December
2 2022-11-12  2022     11   November
3 2023-02-13  2023      2   February
4 2022-11-25  2022     11   November

In [26]:
df1['hour'] =df1['time'].astype(str).str.zfill(4).str[:2].astype(int)
def time_of_day(h):
    if 6<=h<12:
        return'Morning'
    elif 12<=h<17:
       return 'Afternoon'
    elif 17<=h<21:
        return 'Evening'
    else:
       return 'Night'
df1['time_of_day'] = df1['hour'].apply(time_of_day)
df1[['time', 'hour', 'time_of_day']].head()

   time  hour time_of_day
0  1958    19     Evening
1  2245    22       Night
2   250     2       Night
3   545     5       Night
4  2146    21       Night

In [27]:
df1.to_csv('../data/cleaned_accident_data.csv', index=False)